### ISSUE TITLE
"You must specify a region" exception even if region provided

### ISSUE THREAD

**Issue by yi2020** [indeni/dragoneye#38]
For this code (from the README example):
```python
from dragoneye import AwsScanner, AwsCloudScanSettings, AzureScanner, AzureCloudScanSettings, AwsSessionFactory, AzureAuthorizer

aws_settings = AwsCloudScanSettings(
    commands_path='/Users/dev/python/dragoneye/aws_commands_example.yaml',
    account_name='default',
    default_region='us-east-1',
    regions_filter=['us-east-1']
)

session = AwsSessionFactory.get_session(profile_name=None)
AwsScanner(session, aws_settings).scan()
```

I'm getting:
```
* Getting region names
Traceback (most recent call last):
  File "/Users/yoni/Library/Application Support/JetBrains/PyCharmCE2020.3/scratches/scratch.py", line 9, in <module>
    AwsScanner(session, aws_settings).scan()
  File "/Users/yoni/code/dragoneye/dragoneye/utils/misc_utils.py", line 20, in elapsed_wrapper
    return_val = function(*arguments)
  File "/Users/yoni/code/dragoneye/dragoneye/cloud_scanner/aws/aws_scanner.py", line 47, in scan
    region_dict_list = self._create_regions_file_structure(account_data_dir)
  File "/Users/yoni/code/dragoneye/dragoneye/cloud_scanner/aws/aws_scanner.py", line 61, in _create_regions_file_structure
    region_list = self._get_region_list()
  File "/Users/yoni/code/dragoneye/dragoneye/cloud_scanner/aws/aws_scanner.py", line 83, in _get_region_list
    ec2 = self.session.client("ec2")
  File "/Users/yoni/code/dragoneye/venv/lib/python3.9/site-packages/boto3/session.py", line 258, in client
    return self._session.create_client(
  File "/Users/yoni/code/dragoneye/venv/lib/python3.9/site-packages/botocore/session.py", line 834, in create_client
    client = client_creator.create_client(
  File "/Users/yoni/code/dragoneye/venv/lib/python3.9/site-packages/botocore/client.py", line 85, in create_client
    client_args = self._get_client_args(
  File "/Users/yoni/code/dragoneye/venv/lib/python3.9/site-packages/botocore/client.py", line 326, in _get_client_args
    return args_creator.get_client_args(
  File "/Users/yoni/code/dragoneye/venv/lib/python3.9/site-packages/botocore/args.py", line 71, in get_client_args
    final_args = self.compute_client_args(
  File "/Users/yoni/code/dragoneye/venv/lib/python3.9/site-packages/botocore/args.py", line 148, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
  File "/Users/yoni/code/dragoneye/venv/lib/python3.9/site-packages/botocore/args.py", line 220, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/Users/yoni/code/dragoneye/venv/lib/python3.9/site-packages/botocore/args.py", line 302, in _resolve_endpoint
    return endpoint_bridge.resolve(
  File "/Users/yoni/code/dragoneye/venv/lib/python3.9/site-packages/botocore/client.py", line 401, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
  File "/Users/yoni/code/dragoneye/venv/lib/python3.9/site-packages/botocore/regions.py", line 133, in construct_endpoint
    result = self._endpoint_for_partition(
  File "/Users/yoni/code/dragoneye/venv/lib/python3.9/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

Process finished with exit code 1
```

**Comment by Tomerva** [comment]
When you create a **boto session** you need to either:
1. specify a region explicitly: `AwsSessionFactory.get_session(region="us-east-1")`
2. have a region environment variable set for it (AWS_DEFAULT_REGION) 
3. define it in the config:
[default]
region=us-east-1

If none is present, it will throw the above exception.

I dont see this as an issue. This is just how boto does it.

**Comment by yi2020** [comment]
So this is a bit odd:
In the `AwsCloudScanSettings` I define the region. Why not use that? I realize that means that the get_session would need the aws_settings as a parameter, but it doesn't make sense to define the same parameter twice.
